### ISSUE TITLE
In live display “Energy Generated” starts at certain level and not 0

### ISSUE THREAD

**Issue by tclaer** [eNeRGy164/gw2pvo-docker#1]
The plot of Energy Generated starts the day with a certain value.
Plot gives a stable horizontal line until the production of the solar system reaches the moment that production is greater the the starting value. From there plot is OK.

It seems the energy value sent is incorrect.

The script can be updated to send v1=-1 and PVOutput will calculate the energy from power v2.

**Comment by tclaer** [comment]
@eNeRGy164 
The gw2pvo tool by Mark Ruys has a fix for this issue. Could you please also update this docker container?

**Comment by eNeRGy164** [comment]
I can do that when @markruys has created a new release of the tool.

**Comment by tclaer** [comment]
the new release was created

**Comment by tclaer** [comment]
fixed in latest version. thanks!
