### ISSUE TITLE
Max retries exceeded - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jan-dewit** [eNeRGy164/gw2pvo-docker#3]
Since this afternoon, getting the data from the SEMS portal fails, the log shows the following:

WARNING  HTTPSConnectionPool(host='globalapi.sems.com.cn', port=443): Max retries exceeded with url: /api/v1/PowerStation/GetMonitorDetailByPowerstationId (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
--

I am using the docker container with an interval of 15 minutes.

Any idea what might cause this?

**Comment by eNeRGy164** [comment]
If you would enter `https://globalapi.sems.com.cn/` in your browser, you will get the also a invalid certificate message.
Basically, Goodwe let their certificate expire.

**Comment by jan-dewit** [comment]
You are right, this is out of our hands. Thanks for your rocket fast reply :)
I also tried setting GW_REGION to EU, should that change the API URL normally? I don't see any difference. 
Was trying this since the EU site might not have a certificate issue.

**Comment by eNeRGy164** [comment]
Did some digging, the iOS app now uses a different endpoint to log in. Adjusted the code accordingly:
https://github.com/markruys/gw2pvo/pull/42
